# Generated by Django 5.0.6 on 2024-06-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('credits', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('syllabus', models.TextField()),
                ('course_duration', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('prerequisites', models.ManyToManyField(blank=True, to='course.course')),
            ],
        ),
    ]
